apiVersion: v1
kind: Service
metadata:
  name: angular-client
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
  selector:
    app: angular-client
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular-client
  template:
    metadata:
      labels:
        app: angular-client
    spec:
      containers:
      - name: angular-client
        image: clinical-angular-ui:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80